import type { PublicSiteConfig } from './publicSite.types';

export const publicSiteConfig: PublicSiteConfig = {
  variant: 'jt',
  topBar: "Building Guam's Future Together",
  wordmark: {
    mode: 'text',
    title: 'Josh',
    titleSecondary: 'Tina',
    amp: '&',
    subtitle: 'For Governor & Lt. Governor',
  },
  officialInfoUrl: 'https://joshtina.info',
  officialInfoLabel: 'Official campaign info',
  heroEyebrow: 'Official public supporter signup',
  heroTitleMobile: 'Support Josh & Tina for Guam.',
  heroTitleDesktop: 'Support Josh Tenorio and Tina Muña-Barnes for Guam.',
  heroLeadMobile: 'Join the campaign, stay connected, and add your name as a supporter.',
  heroSupportTextMobile: 'Josh Tenorio and Tina Muña-Barnes are building a people-powered campaign across Guam.',
  heroLeadDesktop: 'Join the campaign, stay connected, and help us build momentum across Guam. This is the official place to sign up as a supporter and hear from the campaign.',
  primaryCta: 'Sign up to support',
  secondaryCta: 'Learn more about the campaign',
  featurePanelLabel: 'Josh & Tina supporter network',
  featurePanelImageSrc: '/joshtina-supporter.jpeg',
  featurePanelImageAlt: "Let's Go Guam supporter badge",
  featurePanelKicker: 'A people-powered campaign',
  featurePanelText: 'Every signup helps the campaign identify supporters, stay connected, and organize for election season.',
  signupHeroKicker: "Let's go Guam",
  signupHeroTitle: 'Sign up to support the campaign.',
  signupHeroDescription: 'Add your name, tell us what kind of voter help you may need, and include other supporters in your household if they want to be counted too.',
  signupNetworkTitle: 'Join the supporter network',
  signupNetworkImageSrc: '/joshtina-supporter.jpeg',
  signupNetworkImageAlt: "Let's Go Guam supporter artwork",
  signupMobileDescription: 'Add your information below to join the supporter network and share any voter-help needs with the campaign.',
  consentName: 'Josh & Tina 2026',
  thankYouTitle: "Si Yu'os Ma'åse!",
  thankYouSubtitle: 'Thank you for supporting Josh & Tina.',
  thankYouBody: 'Your signup helps the campaign understand support across Guam and stay connected with people who want to be part of the movement.',
  thankYouImageSrc: '/joshtina-thank-you.avif',
  thankYouImageAlt: 'Thank you for supporting Josh and Tina',
  followLabel: 'Follow the campaign',
  footerContactEmail: 'support@joshtina.info',
  footerContactLabel: 'Get in touch',
  footerMailTitle: 'Mail-in donations',
  footerMailBody: 'PO Box 11031\nTamuning, Guam 96910',
  footerDisclaimer: 'Tenorio Muna-Barnes for Guam · Treasurer: Antoinette “Toni” Sanford · PO Box 11031, Tamuning, Guam 96910',
  appTitle: 'Josh & Tina for Guam | Official Supporter Signup',
  metaDescription: 'Official Josh Tenorio and Tina Muña-Barnes supporter signup. Join the campaign, stay informed, and help build momentum across Guam.',
  cards: {
    supportTitle: 'Show your support',
    supportBody: 'Add your name in a few moments and help the campaign understand where support is growing.',
    informedTitle: 'Stay informed',
    informedBody: 'Receive campaign updates, announcements, and other key moments as the 2026 race moves forward.',
    activityTitle: 'Join campaign activity',
    activityBody: 'Raise your hand for motorcades, events, and other moments where supporters help drive momentum.',
  },
  signupSteps: {
    recordTitle: 'The campaign records your support',
    recordBody: 'Your information helps the campaign understand where support is growing across Guam and which households are ready to engage.',
    helpTitle: 'The campaign can follow up on voter help',
    helpBody: 'If you ask for voter-registration, absentee, homebound, or ride assistance, the team can route that request for follow-up.',
    householdTitle: 'This form supports households too',
    householdBody: 'You can add other supporters in the same household so they become separate records without making staff retype shared address and contact details later.',
  },
  thankYouNextStepTitle: 'Supporter next step',
  thankYouNextStepBody: 'If you opted in for updates, the campaign may reach out with announcements, volunteer opportunities, and event information.',
};
